apiVersion: v1
kind: Service
metadata:
  name: cifar10-serving
  namespace: ml-training

spec:
  type: ClusterIP

  selector:
    app: cifar10-serving

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080