FROM python:3.11-slim

WORKDIR /app

COPY requirements/train.txt requirements/train.txt

RUN pip install --no-cache-dir -r requirements/train.txt

COPY src/ src/
COPY configs/ configs/

RUN mkdir -p data checkpoints

CMD ["python", "src/train.py"]